# Generated by Django 3.0.2 on 2020-02-09 00:14

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200128_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[account.validators.validate_phone]),
        ),
    ]
