# Generated by Django 3.0.2 on 2020-02-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200209_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/profile/profile.jpg', upload_to='media/profiles'),
        ),
    ]
