# Generated by Django 3.0.2 on 2020-02-11 13:01

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(null=True, validators=[account.validators.validate_phone]),
        ),
    ]
