image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: pip3 install -r ./requirements.txt
    command: >
      python3 manage.py migrate &&
      python3 manage.py collectstatic &&
      daphne -b localhost -p 8080 myhome.asgi:application

