# Generated by Django 2.2.7 on 2019-11-25 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_property', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('rooms', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('parking', models.IntegerField(default=0)),
                ('area_built', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('area_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estrato', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=70)),
                ('description', models.TextField(max_length=500)),
                ('type_business', models.CharField(max_length=100)),
                ('seen', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('follower_ids', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='addressCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departamento', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('barrio', models.CharField(max_length=30)),
                ('tipo_via', models.CharField(max_length=30)),
                ('via', models.CharField(max_length=30)),
                ('prefijo_via', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('prefijo_numero', models.CharField(max_length=10)),
                ('placa', models.IntegerField()),
                ('display', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_col', to='properties.Property')),
            ],
        ),
    ]
