# Generated by Django 2.2.8 on 2020-01-28 22:02

import account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citiesapp', '0006_auto_20200103_2006'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SALE / VENTA', 'sale'), ('RENT / ARRENDAMIENTO', 'rent'), ('SWAP / PERMUTA', 'swap')], default='SALE / VENTA', max_length=70, verbose_name='type of business')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='code')),
                ('upload_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='upload-code')),
                ('type_property', models.CharField(choices=[('APT', 'apartment'), ('HOU', 'house'), ('LAN', 'land'), ('FAR', 'farm'), ('COM', 'commercial')], default='APT', max_length=70, verbose_name='type of property')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='price')),
                ('price_str', models.CharField(default='', max_length=18)),
                ('rooms', models.IntegerField(default=0, verbose_name='rooms')),
                ('baths', models.IntegerField(default=0, verbose_name='bathrooms')),
                ('parking', models.IntegerField(default=0, verbose_name='parking')),
                ('area_built', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='built area')),
                ('area_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='total area')),
                ('estrato', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year built')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_slug', models.SlugField(max_length=70)),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('seen', models.IntegerField(default=0, verbose_name='seen')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('promoted', models.BooleanField(default=False, verbose_name='promoted')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(related_name='following', through='properties.Following', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_properties', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type_business', models.ManyToManyField(related_name='business', to='properties.BusinessType', verbose_name='business type')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='img/img_1.jpg', null=True, upload_to='img/')),
                ('main', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.Property')),
            ],
        ),
        migrations.AddField(
            model_name='following',
            name='property_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='properties.Property'),
        ),
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('phone', models.IntegerField(validators=[account.validators.validate_phone], verbose_name='phone')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='message')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='properties.Property')),
            ],
        ),
        migrations.CreateModel(
            name='AddressCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_via', models.CharField(max_length=30)),
                ('via', models.CharField(max_length=30)),
                ('prefijo_via', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.IntegerField()),
                ('prefijo_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('placa', models.IntegerField()),
                ('mostrar', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citiesapp.City')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citiesapp.State')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_col', to='properties.Property')),
            ],
        ),
    ]
