# Generated by Django 2.2.7 on 2019-12-02 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='slug',
            new_name='title_slug',
        ),
        migrations.RemoveField(
            model_name='property',
            name='follower_ids',
        ),
        migrations.AddField(
            model_name='property',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('property_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='properties.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='followers',
            field=models.ManyToManyField(through='properties.Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
