# Generated by Django 2.2.7 on 2019-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20191202_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresscol',
            old_name='display',
            new_name='mostrar',
        ),
        migrations.RemoveField(
            model_name='property',
            name='following',
        ),
        migrations.AlterField(
            model_name='property',
            name='area_built',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='built area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='total area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.IntegerField(default=0, verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.IntegerField(default=0, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.IntegerField(default=0, verbose_name='parking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='seen',
            field=models.IntegerField(default=0, verbose_name='seen'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_business',
            field=models.CharField(max_length=100, verbose_name='type of business'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_property',
            field=models.CharField(max_length=70, verbose_name='type of property'),
        ),
    ]
