# Generated by Django 3.0.2 on 2020-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200209_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=700, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_slug',
            field=models.SlugField(),
        ),
    ]
