# Generated by Django 2.2.7 on 2019-12-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20191203_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_property',
            field=models.CharField(choices=[('APT', 'apartment'), ('HOU', 'house'), ('LAN', 'land')], default='APT', max_length=70, verbose_name='type of property'),
        ),
    ]
