# Generated by Django 3.0.2 on 2020-02-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_pause'),
        ('properties', '0003_auto_20200214_1412'),
    ]

    operations = [
    ]
