# Generated by Django 2.2.7 on 2019-12-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20191205_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_str',
            field=models.CharField(default='', max_length=18),
        ),
    ]
