# Generated by Django 2.2.7 on 2019-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20191213_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='name',
            field=models.CharField(default='none', max_length=20, verbose_name='type of property'),
            preserve_default=False,
        ),
    ]
