# Generated by Django 2.2.7 on 2019-12-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_businesstype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstype',
            name='property',
        ),
    ]
