# Generated by Django 3.0.2 on 2020-03-02 16:21

import django.core.validators
from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200302_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), properties.models.max_value_current_year], verbose_name='built in'),
        ),
    ]
