# Generated by Django 3.0.2 on 2020-03-10 19:21

import django.core.validators
from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20200302_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='facilities')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='area_pro',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Project area'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), properties.models.max_value_current_year], verbose_name='built in'),
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.ManyToManyField(related_name='facilities', to='properties.Facility', verbose_name='facilities'),
        ),
    ]
