# Generated by Django 3.0.2 on 2020-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200310_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths_max',
            field=models.IntegerField(default=0, verbose_name='bathrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_max',
            field=models.IntegerField(default=0, verbose_name='parking'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms_max',
            field=models.IntegerField(default=0, verbose_name='rooms'),
        ),
    ]
