# Generated by Django 2.2.7 on 2019-12-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20191213_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type_business',
        ),
        migrations.AddField(
            model_name='property',
            name='type_business',
            field=models.ManyToManyField(related_name='business', to='properties.BusinessType'),
        ),
    ]
