# Generated by Django 2.2.7 on 2019-12-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20191213_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresscol',
            old_name='Departamento',
            new_name='departamento',
        ),
    ]
