# Generated by Django 3.0.2 on 2020-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200311_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths_max',
            field=models.IntegerField(default=0, verbose_name='bathrooms max'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_max',
            field=models.IntegerField(default=0, verbose_name='parking max'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms_max',
            field=models.IntegerField(default=0, verbose_name='rooms max'),
        ),
    ]
