# Generated by Django 3.0.2 on 2020-03-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20200311_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area_pro',
        ),
        migrations.AddField(
            model_name='property',
            name='area_max',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Project max'),
        ),
    ]
