# Generated by Django 2.2.7 on 2019-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20191216_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='name',
            field=models.CharField(choices=[('SAL', 'sale'), ('REN', 'rent'), ('EXC', 'swap')], default='SAL', max_length=70, verbose_name='type of business'),
        ),
    ]
