# Generated by Django 2.2.7 on 2019-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20191217_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_business',
            field=models.ManyToManyField(related_name='business', to='properties.BusinessType', verbose_name='business type'),
        ),
    ]
