# Generated by Django 2.2.7 on 2019-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20191217_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='name',
            field=models.CharField(choices=[('SALE', 'sale'), ('RENT', 'rent'), ('SWAP', 'swap')], default='SALE', max_length=70, verbose_name='type of business'),
        ),
    ]
