# Generated by Django 2.2.7 on 2019-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20191217_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type_business',
        ),
        migrations.AddField(
            model_name='property',
            name='type_business',
            field=models.CharField(choices=[('SALE', 'sale'), ('RENT', 'rent'), ('SWAP', 'swap')], default='SALE', max_length=70, verbose_name='type of business'),
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
    ]
