# Generated by Django 2.2.7 on 2019-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20191217_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SALE', 'sale'), ('RENT', 'rent'), ('SWAP', 'swap')], default='SALE', max_length=70, verbose_name='type of business')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='type_business',
        ),
        migrations.AddField(
            model_name='property',
            name='type_business',
            field=models.ManyToManyField(related_name='business', to='properties.BusinessType', verbose_name='business type'),
        ),
    ]
