# Generated by Django 2.2.7 on 2019-12-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20191217_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='img/img_1.jpg', null=True, upload_to='img/')),
                ('main', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.Property')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
