# Generated by Django 2.2.7 on 2019-12-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_auto_20191217_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
    ]
