# Generated by Django 2.2.7 on 2020-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20191218_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_property',
            field=models.CharField(choices=[('APT', 'apartment'), ('HOU', 'house'), ('LAN', 'land'), ('COM', 'commercial')], default='APT', max_length=70, verbose_name='type of property'),
        ),
    ]
