# Generated by Django 2.2.7 on 2020-01-02 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_auto_20200102_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='properties.Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
