# Generated by Django 2.2.7 on 2020-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
