# Generated by Django 2.2.7 on 2020-01-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_auto_20200102_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscol',
            name='prefijo_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addresscol',
            name='prefijo_via',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
