# Generated by Django 2.2.8 on 2020-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_auto_20200103_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year built'),
        ),
    ]
