# Generated by Django 2.2.8 on 2020-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_property_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upload_code',
            field=models.IntegerField(default=0, verbose_name='upload-code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_property',
            field=models.CharField(choices=[('APT', 'apartment'), ('HOU', 'house'), ('LAN', 'land'), ('FAR', 'farm'), ('COM', 'commercial')], default='APT', max_length=70, verbose_name='type of property'),
        ),
    ]
