# Generated by Django 2.2.8 on 2020-01-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_auto_20200109_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscol',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citiesapp.City'),
        ),
        migrations.AlterField(
            model_name='addresscol',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citiesapp.State'),
        ),
    ]
