# Generated by Django 3.0.2 on 2020-01-28 19:23

import account.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0006_auto_20200103_2006'),
        ('properties', '0033_auto_20200109_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='property',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='promoted'),
        ),
        migrations.AlterField(
            model_name='addresscol',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citiesapp.City'),
        ),
        migrations.AlterField(
            model_name='addresscol',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citiesapp.State'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(validators=[account.validators.validate_phone]),
        ),
    ]
