# Generated by Django 2.2.8 on 2020-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_auto_20200116_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
