# Generated by Django 2.2.8 on 2020-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_property_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='promoted'),
        ),
    ]
