# Generated by Django 2.2.8 on 2020-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_auto_20200123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
