# Generated by Django 2.2.8 on 2020-01-23 20:34

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_auto_20200123_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(validators=[account.validators.validate_phone]),
        ),
    ]
