# Generated by Django 2.2.8 on 2020-01-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_auto_20200123_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='message'),
        ),
    ]
