# Generated by Django 2.2.8 on 2020-01-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.IntegerField()),
                ('iso2', models.CharField(max_length=10)),
                ('iso3', models.CharField(max_length=10)),
            ],
        ),
    ]
