# Generated by Django 2.2.8 on 2020-01-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
