# Generated by Django 2.2.8 on 2020-01-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0003_auto_20200102_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.IntegerField(),
        ),
    ]
