# Generated by Django 2.2.8 on 2020-01-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0005_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
